GET https://reqres.in/api/users HTTP/1.1


###
POST https://reqres.in/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Test01Levanter",
    "job":"Developer"
}
###
GET http://localhost:7000/blog HTTP/1.1

###
POST http://localhost:7000/posts HTTP/1.1
Content-Type: application/json

{
    "title" : "All is your fault test 02",
        "content" : "The new band test 02",
        "imageUrl":"Image null test 02",
        "categoryId":90,
        "userId":1
}